name: regressis-docs

channels:
- defaults
- conda-forge

dependencies:
- python=3.8
- numpy
- matplotlib
- scikit-learn
- fitsio
- healpy
- astropy
- pip:
    - git+https://github.com/echaussidon/regressis
